# Generated by Django 5.2.5 on 2025-10-04 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('Sequential', 'Sequential Multi-Level'), ('Percentage', 'Percentage Rule'), ('SpecificApprover', 'Specific Approver Rule'), ('Hybrid', 'Hybrid (Sequential + Conditional)')], default='Sequential', max_length=20)),
                ('percentage_threshold', models.IntegerField(blank=True, help_text='e.g., 60 means 60% of approvers must approve', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default workflow for this company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='companies.company')),
                ('specific_approver', models.ForeignKey(blank=True, help_text='e.g., CFO - if this person approves, auto-approve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_approval_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_workflows',
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('step_number', models.IntegerField(help_text='0 = Manager, 1+ = Workflow steps')),
                ('decision', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='expenses.expense')),
            ],
            options={
                'db_table': 'expense_approvals',
                'ordering': ['step_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(help_text='1 = Finance, 2 = Director, etc.')),
                ('approver_title', models.CharField(blank=True, help_text='e.g., Finance, Director, CFO', max_length=100)),
                ('approver', models.ForeignKey(limit_choices_to={'role__in': ['Manager', 'Admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_assignments', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvals.approvalworkflow')),
            ],
            options={
                'db_table': 'workflow_approvers',
                'ordering': ['sequence'],
                'unique_together': {('workflow', 'sequence')},
            },
        ),
    ]
