# Generated by Django 5.2.5 on 2025-10-04 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_currency', models.CharField(max_length=10)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Amount converted to company's default currency", max_digits=12, null=True)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food & Dining'), ('Accommodation', 'Accommodation'), ('Office', 'Office Supplies'), ('Transport', 'Transportation'), ('Entertainment', 'Client Entertainment'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('expense_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('current_step', models.IntegerField(default=0, help_text='Current approval step (0 = manager, 1+ = workflow steps)')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('ocr_extracted_text', models.TextField(blank=True, null=True)),
                ('ocr_merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ocr_extracted_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company')),
                ('current_approver', models.ForeignKey(blank=True, help_text='Current person who needs to approve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
