# Generated by Django 5.2.5 on 2025-10-04 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='merchant_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_confidence_score',
            field=models.FloatField(blank=True, help_text='OCR accuracy confidence (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_extracted_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='OCR processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, choices=[('Travel', 'Travel'), ('Food', 'Food & Dining'), ('Accommodation', 'Accommodation'), ('Office', 'Office Supplies'), ('Transport', 'Transportation'), ('Entertainment', 'Client Entertainment'), ('Other', 'Other')], max_length=50, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expenses.expense')),
            ],
            options={
                'db_table': 'expense_line_items',
                'ordering': ['created_at'],
            },
        ),
    ]
